export const COMPANY_INTRODUCTION_REQUEST = "COMPANY_INTRODUCTION_REQUEST"
export const COMPANY_INTRODUCTION_SUCCESS = "COMPANY_INTRODUCTION_SUCCESS"
export const COMPANY_INTRODUCTION_FAILURE = "COMPANY_INTRODUCTION_FAILURE"